### ISSUE TITLE
Create new tests for WebService 8.0.0-RC30

### ISSUE THREAD

**Issue by lxatstariongroup** [STARIONGROUP/ecss-10-25-annexc-integration-tests#57]
- [x] Create test for create new Option on model having a OptionDependent Parameter: https://github.com/STARIONGROUP/COMET-WebServices-Community-Edition/issues/351

- [x] [Create test for [FIX] Error saving value to ParameterSubscription on ParameterOverride: https://github.com/STARIONGROUP/COMET-WebServices-Community-Edition/issues/355

- [ ] Create test for fix/gh353-Change-Ownership-on-OptionDependent-Parameter-overwrites-existing-valuesets: https://github.com/STARIONGROUP/COMET-WebServices-Community-Edition/issues/353
